### ISSUE TITLE
Не работает добавление кастомных полей типа список

### ISSUE THREAD

**Issue by bigperson** [linkprofit-cpa/amocrm-api#12]
При передаче в enum строки со значениями через запятую amocrm возвращает 400 ошибку (хотя в документации и сказано что можно передавать как строки так и массив).
Как вариант передавать вместо строки массив https://github.com/linkprofit-cpa/amocrm-api/blob/master/src/entities/Field.php#L184-L185  заменить на:
```php
public function linkEnumArray(array $enums = [])
{
    $this->enums = $enums;
}
```

**Comment by Phrlog** [comment]
Хм, может им в поддержку написать?

**Comment by Phrlog** [comment]
@bigperson 
написал, они спросили проверял ли я работу метода в консоли разработчика – http://amo.sh/O6EETR/F3UQF3

можешь проверить?

**Comment by bigperson** [comment]
@Phrlog Я им писал и не получил внятного ответа, в консоли разработчика проверял и там нельзя указать строку, она автоматом парсится в массив

![image](https://user-images.githubusercontent.com/4757391/41156389-5ab412dc-6b2a-11e8-9afe-63a075420b93.png)

**Comment by bigperson** [comment]
Временное решение напрямую указать enums как свойство без сеттера
```php
$field = new Field();
$field->enums = ['value1', 'value2', 'value3']; 
```

**Comment by Phrlog** [comment]
Ну да, свойство публичное. 

В любом случае, если в поддержке ничего внятного не ответят, исправлю метод на твой вариант.
