### ISSUE TITLE
Пагинация списка элементов

### ISSUE THREAD

**Issue by bigperson** [linkprofit-cpa/amocrm-api#8]
Добавляю чтоб не забыть. 

Из переписки с техподдержкой выяснилось, что (в доке по элементам списка этого нету):

> Вы можете добавить вот эти два GET параметра для сдвига, так же вы можете ограничить количество сущностей в ответе. &limit_rows=500&limit_offset=500 в данном случае вам вернутся следующие 500 элементов, либо все что есть в остатке после первых 500. 

Предлагаю вынести в базовый сервис или трейт метод [list()](https://github.com/linkprofit-cpa/amocrm-api/blob/master/src/services/CatalogElementService.php#L39), и подключать в тех сервисах, где есть возможность получения списка сущностей, добавив опциональные параметры limit и offset, поскольку получение сущностей помимо списков доступно:

- в контактах
- в сделках
- в покупателях
- в компаниях
- в задачах
- в примечаниях
- и т.д. надо всю доку пересмотреть

Проблема в том что разные сущности требуют разные обязательные параметры для выборки, где-то тип элемента, где-то id каталога и т.д, либо сделать абстрактный метод в базовом классе который реализовывать в каждом сервисе.

**Comment by Phrlog** [comment]
Думаю, можно добавить интерфейс Listable или что-то вроде того

Еще можно сделать трейт для пагинации, в нем хранить свойства limit и
offset, сделать методы limit() и offset(), которые меняют свойства и
возвращают $this, чтоб можно было цепочкой вызывать –
$service->limit(10)->offset(5)->list();

И отдельно для каждого сервиса прописывать метод с обязательным параметром
– id каталога, тип элемента и т.д – который тоже возвращает $this

Пока конкретней не могу ничего предложить

16 мая 2018 г., 15:12 пользователь Anton Kartsev <notifications@github.com>
написал:
